id: IAAEC3524
legacy_id: P000378
ocr_import_info:
  bdrc_scan_id: W1KG14473
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T12:06:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T06:54:05.840856+00:00'
last_modified: 2022-08-31 14:54:29.888593
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14473
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14473
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇམ་དཔལ་གཤིན་རྗེའི་གཤེད་ཁྲོ་ཆུ་དུག་སྡོང་ནག་པོའི་ཆོས་སྐོར།
  author: རྒྱ་ཞང་ཁྲོམ་རྡོ་རྗེ་འོད་འབར།
statistics:
  ocr_word_mean_confidence_index: 0.5350723281619352
  ocr_word_median_confidence_index: 0.5199999809265137
quality: null
bases:
  I1KG14477:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14477
      total_pages: 568
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG14477.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5640567318038122
    legacy_id: v001
  I1KG14478:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14478
      total_pages: 562
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG14478.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5022689449481449
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
